# Generated by Django 5.1.4 on 2024-12-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_name', models.CharField(max_length=30)),
                ('director_title', models.CharField(max_length=40)),
                ('director_phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
