# Generated by Django 5.1.4 on 2024-12-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='directors',
            new_name='director',
        ),
    ]
