# Generated by Django 5.1.4 on 2024-12-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_directors_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_date', models.DateField()),
                ('announcement_title', models.CharField(max_length=20)),
                ('announcement_image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
