# Generated by Django 5.1.4 on 2024-12-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_announcements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='announcements',
            new_name='announcement',
        ),
    ]
