# Generated by Django 5.1.4 on 2024-12-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_announcements_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='announcement',
        ),
        migrations.AddField(
            model_name='director',
            name='director_image',
            field=models.ImageField(default='', upload_to='website/images'),
        ),
    ]
