# Generated by Django 5.1.4 on 2024-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_announcement_director_director_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=30)),
                ('Product_desc', models.CharField(max_length=40)),
                ('Product_image', models.ImageField(default='', upload_to='website/products/images')),
            ],
        ),
    ]
