# Generated by Django 5.1.4 on 2024-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualReport_year', models.CharField(max_length=30)),
                ('AnnualReport_image', models.ImageField(default='', upload_to='website/AnnualReport/images')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(max_length=30)),
                ('Branch_address', models.CharField(max_length=100)),
                ('Branch_phone', models.IntegerField(max_length=10)),
                ('Branch_image', models.ImageField(default='', upload_to='website/Branch/images')),
            ],
        ),
        migrations.CreateModel(
            name='NewsandUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('News_date', models.DateField()),
                ('News_title', models.CharField(max_length=20)),
                ('News_desc', models.CharField(max_length=30)),
                ('News_image', models.ImageField(default='', upload_to='website/News/images')),
            ],
        ),
    ]
