# Generated by Django 5.1.4 on 2024-12-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_annualreport_branch_newsandupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Officetitle', models.CharField(max_length=20)),
                ('Officeaddress', models.CharField(max_length=40)),
                ('Logo', models.ImageField(default='', upload_to='website/HomeSlide/images/logo')),
                ('Banner', models.ImageField(default='', upload_to='website/HomeSlide/images/banner')),
                ('Phone1', models.IntegerField()),
                ('Phone2', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
