# Generated by Django 5.1.4 on 2024-12-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_homeslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='Branch_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_phone',
            field=models.IntegerField(),
        ),
    ]
