# Generated by Django 5.1.4 on 2024-12-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_branch_branch_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='AboutLong',
            field=models.CharField(default='fdhjs', max_length=600),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='AboutShort',
            field=models.CharField(default='jfdskkndnnvkldskl', max_length=60),
        ),
    ]
