# Generated by Django 5.1.4 on 2024-12-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_homeslide_aboutlong_homeslide_aboutshort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='AboutLong',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='AboutShort',
            field=models.CharField(max_length=60),
        ),
    ]
