# Generated by Django 5.1.4 on 2024-12-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_homeslide_registrationnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslide',
            name='AboutLong',
        ),
        migrations.RemoveField(
            model_name='homeslide',
            name='AboutShort',
        ),
        migrations.AddField(
            model_name='homeslide',
            name='About',
            field=models.CharField(default=' was established in 1956 as a Multistate Cooperative Society under Registration No: MSCS/CR/208/2005 - 231,Dall Mill,Sarai Pipal Thala Azadpur ,Delhi - 110033 our society has been dedicated to supporting the agricultural community for decades.', max_length=60),
        ),
    ]
