# Generated by Django 5.1.4 on 2024-12-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_homeslide_about_alter_homeslide_officeaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='Establishedyear',
            field=models.IntegerField(default=2024, max_length=4),
            preserve_default=False,
        ),
    ]
