# Generated by Django 5.1.4 on 2024-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_homeslide_establishedyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslide',
            name='About',
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='Establishedyear',
            field=models.IntegerField(default='2024', max_length=4),
        ),
    ]
