# Generated by Django 5.1.4 on 2024-12-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_homeslide_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='Registrationnumber',
            field=models.CharField(default='MSCS/CR/208/2005', max_length=25),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='Title',
            field=models.CharField(max_length=100),
        ),
    ]
