# Generated by Django 5.1.4 on 2024-12-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_homeslide_registrationnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Title', models.CharField(max_length=100)),
                ('About_Establishedyear', models.IntegerField(default='2024', max_length=4)),
                ('About_Registrationnumber', models.CharField(default='MSCS/CR/208/2005', max_length=25)),
                ('Aboutpage_image', models.ImageField(default='', upload_to='website/HomeSlide/images/logo')),
                ('Aboutpage_visionimage', models.ImageField(default='', upload_to='website/HomeSlide/images/banner')),
                ('About_visionpara', models.CharField(max_length=100)),
                ('About_missionpara', models.CharField(max_length=100)),
            ],
        ),
    ]
