# Generated by Django 5.1.4 on 2024-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_aboutus_aboutpage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='About_missionimage',
            field=models.ImageField(default='', upload_to='website/Aboutpage/images/missionimage'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='About_missionpara',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='About_visionpara',
            field=models.CharField(max_length=1000),
        ),
    ]
