# Generated by Django 5.1.4 on 2024-12-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_aboutus_about_missionimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='About_middleimage',
            field=models.ImageField(default='', upload_to='website/Aboutpage/images/middleimage'),
        ),
    ]
