# Generated by Django 5.1.4 on 2024-12-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_aboutus_about_middleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='About_middleimage',
            field=models.ImageField(upload_to='website/Aboutpage/images/middleimage'),
        ),
    ]
