# Generated by Django 5.1.4 on 2024-12-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_aboutus_about_middleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Byelaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Byelaw_document', models.ImageField(default='', upload_to='website/Byelaws')),
            ],
        ),
    ]
