# Generated by Django 5.1.4 on 2024-12-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_byelaws'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Byelaws',
            new_name='Byelaw',
        ),
    ]
