# Generated by Django 5.1.4 on 2024-12-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_rename_byelaws_byelaw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byelaw',
            name='Byelaw_document',
            field=models.FileField(default='', upload_to='website/Byelaws'),
        ),
    ]
