# Generated by Django 5.1.4 on 2024-12-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_byelaw_byelaw_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreport',
            name='AnnualReport_file',
            field=models.FileField(default='', upload_to='website/AnnualReport'),
        ),
    ]
