# Generated by Django 5.1.4 on 2024-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_director_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='Aboutpage_fertilizer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
