# Generated by Django 5.1.4 on 2024-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_aboutus_aboutpage_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='aboutimage',
            field=models.ImageField(default='', upload_to='website/HomeSlide/images/about'),
        ),
    ]
