# Generated by Django 5.1.4 on 2024-12-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='Home_news_date',
            field=models.DateField(default='2004-01-01'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='Home_news_image',
            field=models.ImageField(default='', upload_to='website/HomeSlide/images/news'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='Home_news_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
