# Generated by Django 5.1.4 on 2024-12-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_homeslide_home_news_date_homeslide_home_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsandupdate',
            name='News_attachment',
            field=models.FileField(default='', upload_to='website/News/Attachments'),
        ),
    ]
