# Generated by Django 5.1.4 on 2024-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_newsandupdate_news_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='Home_news_attachment',
            field=models.FileField(default='', upload_to='websit/HomeSlide/attachment'),
        ),
    ]
