# Generated by Django 5.1.4 on 2025-01-01 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_homeslide_home_news_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeslide',
            old_name='Officeaddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='homeslide',
            old_name='Title',
            new_name='Heading',
        ),
        migrations.RenameField(
            model_name='homeslide',
            old_name='Officetitle',
            new_name='Officetype',
        ),
        migrations.RenameField(
            model_name='homeslide',
            old_name='Home_news_attachment',
            new_name='news_Attachment',
        ),
        migrations.RenameField(
            model_name='homeslide',
            old_name='Home_news_date',
            new_name='news_date',
        ),
        migrations.RenameField(
            model_name='homeslide',
            old_name='Home_news_title',
            new_name='news_heading',
        ),
        migrations.RenameField(
            model_name='homeslide',
            old_name='Home_news_image',
            new_name='news_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='About_Establishedyear',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='About_Registrationnumber',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='About_Title',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='About_middleimage',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='About_missionimage',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='Aboutpage_image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='Aboutpage_visionimage',
        ),
        migrations.RemoveField(
            model_name='homeslide',
            name='aboutimage',
        ),
    ]
