# Generated by Django 5.1.4 on 2025-01-01 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_rename_officeaddress_homeslide_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreport',
            name='AnnualReport_year',
        ),
    ]
